---
- name: Set OS-specific variables
  ansible.builtin.set_fact:
    nginx_user: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"
    nginx_group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"

- name: Setup Base settings
  ansible.builtin.include_tasks: base_settings.yml

- name: Setup UFW
  ansible.builtin.include_tasks: setup_ufw.yml

- name: Setup SSL certificate
  ansible.builtin.include_tasks: setup_ssl.yml
  when: certbot_enabled | default(true)

- name: Configure HTTPS sites
  ansible.builtin.include_tasks: configure_sites.yml
