- name: Создание директории
  file:
    path: "{{ project_root }}"
    state: directory
    mode: '0755'


- name: Клонировать репозиторий с токеном в URL
  ansible.builtin.git:
    repo: "https://{{ gitflic_username }}:{{ gitflic_token }}@gitflic.ru/{{ git_url_ending }}"
    dest: "{{ project_root }}"
    version: "{{ version }}"

# - name: Клонировать публичный репозиторий
#   ansible.builtin.git:
#     repo: "{{ git_url_repo }}"
#     dest: "{{ project_root }}"
#     version: "{{ version }}"
#     update: yes


- name: Копирование .env файла из шаблона
  template:
    # src: ../templates/.env.j2
    src: .env.j2
    dest: "{{ project_root }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600


- name: Запуск контейнеров
  community.docker.docker_compose_v2:
    # env_files:
    #   - "{{project_root }}/.env"
    project_src: "{{ project_root }}"
    pull: missing
    state: present


- name: Вывод информации о развёртывании
  debug:
    msg:
      - ✅ Проект успешно развёрнут!
      - "🌐 Адрес: http://{{ ansible_default_ipv4.address }}"
      # - "🔑 Логин по умолчанию: glpi / glpi"


