- name: Создание директории
  file:
    path: "{{ project_root }}"
    state: directory
    mode: '0755'
    # recurse: yes  # Создаст все родительские директории, если их нет


# - name: Убедиться, что SSH-ключ установлен
#   ansible.builtin.copy:
#     src: {{ path_ssh_privat_key_src }}
#     dest: {{ path_ssh_privat_key_trg }}
#     mode: 0600


# - name: Клонировать приватный репозиторий через SSH
#   ansible.builtin.git:
#     repo: {{ git_url_repo }}
#     dest: {{ project_root }}
#     version: {{ version }}
#     key_file: {{ path_ssh_privat_key_trg }}
#     accept_hostkey: yes
#     update: yes


- name: Клонировать публичный репозиторий
  ansible.builtin.git:
    repo: "{{ git_url_repo }}"
    dest: "{{ project_root }}"
    version: "{{ version }}"
    update: yes


- name: Копирование .env файла из шаблона
  template:
    # src: ../templates/.env.j2
    src: .env.j2
    dest: "{{ project_root }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600


- name: Запуск контейнеров
  community.docker.docker_compose_v2:
    # env_files:
    #   - "{{project_root }}/.env"
    project_src: "{{ project_root }}"
    pull: missing
    state: present


- name: Вывод информации о развёртывании
  debug:
    msg:
      - ✅ Проект успешно развёрнут!
      - "🌐 Адрес: http://{{ ansible_default_ipv4.address }}"
      # - "🔑 Логин по умолчанию: glpi / glpi"
