- name: "1. Создание директории для GLPI"
  file:
    path: "{{ project_root }}"
    state: directory
    mode: '0755'
    # recurse: yes  # Создаст все родительские директории, если их нет

- name: 2. Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ project_root }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: "3. Копирование .env файла из шаблона"
  template:
    src: ../templates/.env.j2
    dest: "{{ project_root }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: "4. Запуск контейнеров"
  community.docker.docker_compose_v2:
    env_files:
      - "{{project_root }}/.env"
    project_src: "{{ project_root }}"
    pull: missing
    state: present

# - name: "5. Проверка GLPI"

- name: "6. Вывод информации о развёртывании"
  debug:
    msg:
      - "✅ GLPI успешно развёрнут!"
      - "🌐 Адрес: http://{{ ansible_default_ipv4.address }}"
      # - "🔑 Логин по умолчанию: glpi / glpi"
