---
all:
  children:
    nextcloud:
      hosts:
        srv-2.dyuzha.ru:
          ansible_user: root
          # ansible_python_interpreter: /usr/bin/python3.9
          ansible_python_interpreter: /usr/libexec/platform-python
          # ansible_python_interpreter: /usr/bin/python3.12
